### ISSUE TITLE
建议右键发送到 aria2 应该支持 https 链接

### ISSUE THREAD

**Issue by ashfinal** [miniers/safari2aria#1]
直接接管 https 链接点击事件，由于苹果限制可能做不到。
但是右键发送到 aria2 感觉应该没问题？毕竟只需获取当前链接，构造请求发给 aria2 RPC 服务就行。
因为目前浏览的网站基本都是 https 的，而必须先给 aria2 添加证书感觉挺麻烦的。

对前端 js 等了解不多，可能说的不对 …… 总之，有可能的话，希望给右键发送添加 https 的支持。

**Comment by miniers** [comment]
safari中在HTTPS页面访问HTTP资源是被禁止的，这个属于W3C的规范包括在safari 扩展中也需要遵守这一规则。估计这个问题暂时无法解决了。
可以参考这篇文章：[https://imququ.com/post/sth-about-switch-to-https.html#toc-0-2](https://imququ.com/post/sth-about-switch-to-https.html#toc-0-2)

而且给aria2加证书属于一劳永逸的做法，只需要麻烦一次。

另外提供一枚申请免费证书的网站[assl.loovit.net](assl.loovit.net),该网站可以申请泛域名证书。

**Comment by ashfinal** [comment]
谢谢回复。看来右键确实没法支持 https ;(
那我只想在本机上使用 aria2，怎么添加证书呢？

**Comment by miniers** [comment]
提供一枚解析到127.0.0.1的域名证书
域名为  aria2.zc.ci
[aria2.zc.ci.zip](https://github.com/miniers/safari2aria/files/1070942/aria2.zc.ci.zip)

**Comment by miniers** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--rpc-certificate
这里有原版配置方法

**Comment by ashfinal** [comment]
经过半天折腾，终于好使了。非常感谢！

**Comment by miniers** [comment]
仔细研读官方扩展文档，通过其他方式实现了在https页面访问http的问题，最新版已支持

**Comment by ashfinal** [comment]
赞！http 对多数人还是省事点。
