### ISSUE TITLE
界面显示不正常

### ISSUE THREAD

**Issue by linwolfer** [miniers/safari2aria#10]
为什么我的界面显示成这样？？
<img width="402" alt="1" src="https://user-images.githubusercontent.com/26462278/29742752-08ca5ce6-8ab7-11e7-9c2d-3317de9655e4.png">

**Comment by miniers** [comment]
safari版本多少？如果低于10，因为不支持woff2字体就会成这样，这个问题暂时不准备解决

**Comment by linwolfer** [comment]
我用的是 OS X EI Capitan 10.11.6版本，Safari  版本 9.1.2.

感谢你的回复，更感谢你的作品，期待新的佳作。谢谢  👍

**Comment by vinewx** [comment]
osx10.10.6系统，safari版本10.1.2也有同样的问题，根据[官方文档](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html)，以及[某推特](https://twitter.com/bram_stein/status/796860553914302464)表明woff2字体仅支持Sierra系统下的Safari

> Web Open Font Format (WOFF) 2.0 support in Safari on macOS 10.12 and iOS 10 improves compression of website fonts, so fonts require less bandwidth to load.

老系统只能观望了

**Comment by miniers** [comment]
抽空加上别的字体😂

**Comment by miniers** [comment]
O了，加上了woff ，应该可以支持了😂，没老版本系统没法测

**Comment by vinewx** [comment]
现在能正常显示了 👍 👍

**Comment by linwolfer** [comment]
显示正常了，谢谢。

2017年9月4日 +0800 AM9:25 vinewx <notifications@github.com>，写道：
