### ISSUE TITLE
无法将文件推送到NAS上

### ISSUE THREAD

**Issue by gyw920812** [miniers/safari2aria#13]
作者你好，首先感谢开发出这么好用的工具～
我今天安装使用后遇到了一个奇怪的问题，几经查询没有发现原因，特来讨教。
我有两个aria2，一个部署在NAS上，一个部署在mac上。部署在mac上的aria2和您的插件配合正常，下载拦截、推送都没问题。
问题来了，部署在nas上的aria2我无论怎么尝试都无法推送文件上去，提示“Fail to added to xxx”。
现已排除如下情况：（1）aria2本身不正常：用其他gui及命令行方式在nas上的aria2启动文件下载，在您的插件上可以正常显示出下载进度；（2）下载的文件有问题：同一地址的文件推送到mac的aria2上正常，推送到nas上就是不行。
另外，我在命令行下看了一下，浏览器上推送到nas的aria上时，是没有任何反应的
我浏览器版本为safari 11.0，Mac上的aria2版本为1.32.0，nas上的aria2版本为1.14.2（我这个型号的nas（群晖ds214play）上找不到适配的更新版本的aria2了）。
我下载的文件为 https://www.ragnaroks.org/vps/vps-download-speed-test.html 这个页面上随便找的标准大小测速文件。

还请不吝赐教。
万分感谢。

**Comment by miniers** [comment]
设置页面取消勾选nas的推送选项试试，勾选推送会使用websocket连接，有可能低版本aria2不支持

**Comment by gyw920812** [comment]
刚才试了下，无效。。。

**Comment by gyw920812** [comment]
会不会跟aria2 RPC HTTP 请求方法有关。。？

**Comment by miniers** [comment]
周一有空我试试这个版本aria2

**Comment by gyw920812** [comment]
嗯，麻烦啦～

**Comment by miniers** [comment]
尝试编译这个版本的aria2，老是失败，先打包个能输出错误信息的版本。你再看下输出的错误信息是啥
[safari2aria_debug.safariextz.zip](https://github.com/miniers/safari2aria/files/1328050/safari2aria_debug.safariextz.zip)

**Comment by gyw920812** [comment]
![8fc0ba12-d773-40e4-a57d-e3b489ff80e2](https://user-images.githubusercontent.com/32235556/30809369-0e3e8a8c-a234-11e7-944e-4a7e19df5a65.jpg)
感觉还是版本太低不支持某些参数的问题
检查了一下nas上aria2的设置文件，确定是没有这条的。

**Comment by miniers** [comment]
😂，这个参数是插件传过去的，为了解决下载中文名文件乱码，给你打包个不带参数的吧，近期暂时无更新计划，回头加上配置项
[safari2aria_debug.safariextz.zip](https://github.com/miniers/safari2aria/files/1331338/safari2aria_debug.safariextz.zip)

**Comment by gyw920812** [comment]
已经可以成功添加了。感谢~
某些奇葩型号的NAS上aria2的版本都挺老的了，所以确实需要加个配置项。

再次感谢~

**Comment by gyw920812** [comment]
您给我的这个版本好像有。。嗯。。无法保存配置的bug。。safari彻底退出之后就得重新添加aria2设置了😂😂

**Comment by miniers** [comment]
没理由啊，只把参数去掉了，别的都没动😂。把插件删了再装试试吧，

**Comment by gyw920812** [comment]
重装之后好了，谢谢。
