### ISSUE TITLE
配置的wiki能否更详细些？

### ISSUE THREAD

**Issue by loulijun** [miniers/safari2aria#15]
安装完safari2aria后就不知道该怎么配置了，wiki里面也没有写具体步骤，说下我的疑惑
1. 是否需要本地再配置aria2？就是safari2aria的完整配置环境
2. 如何下载？不知道截图里面的“发送至mac”是怎么配置出来的
3. 试了下载一个文件依然是用原有的下载方式，不知道拦截还需要配置什么

所以作者能否更详细傻瓜式的完善下wiki？看了实在是不知道怎么使用，谢谢啦

**Comment by miniers** [comment]
请自行搜索aria2的相关搭建教程
