### ISSUE TITLE
Finder打开失效

### ISSUE THREAD

**Issue by davidkane0526** [miniers/safari2aria#18]

**Comment by phoenixwu** [comment]
我也看不懂readme，「在Finder中顯示」這個功能，應該如何運作？

**Comment by miniers** [comment]
需要配合release中的safari2aria.app来实现，这是一个用Applescript写的小程序，用以通过指定的url scheme协议来打开指定位置

**Comment by phoenixwu** [comment]
那請問具體是在什麼場合下運作呢？我已執行過一次safari2aria.app，接下來要做什麼？在finder做什麼動作？

**Comment by miniers** [comment]
本人对applescript也不是很熟悉，暂时无法排查某些时候 在Finder中顯示  这个功能失效的原因，可以忽略这个功能😂

**Comment by phoenixwu** [comment]
我今天明白了，原來「在finder中顯示」是在local執行aria2的場合使用的
我一直都是配合遠端的aria2使用，難怪怎麼按「在finder中顯示」都沒用 囧
