### ISSUE TITLE
关闭拦截后，cmd+图片 在新标签页打开图片，也会被添加到Aria2下载

### ISSUE THREAD

**Issue by livc** [miniers/safari2aria#20]
请问怎么破？

**Comment by livc** [comment]
这个问题总是出现不知道怎么回事，按理说应该cmd+shift+ pdf或图片的链接才会被添加到Aria2，但是经常cmd+链接就直接下载去了，而不是在新标签页打开。

**Comment by miniers** [comment]
README已经有说明
关闭拦截的情况下，长按CMD会临时启用拦截
可以把自动拦截的文件类型删除对应的后缀名就好

**Comment by livc** [comment]
为什么要用一个和Safari冲突的快捷键？

**Comment by miniers** [comment]
本来想搞自定义快捷键，半年来工作和家的事儿太多，没时间折腾了
可以在 https://github.com/miniers/safari2aria/blob/master/src/public/downloadAble.js
这个文件根据自己的需求手动改下按键判断就好了，
具体的按键key定义在 https://github.com/miniers/safari2aria/blob/master/src/js/endscript/index.js 的 173行下边
