### ISSUE TITLE
百度盘下载名字包含中文的文件会被转换成unicode码怎么解决？

### ISSUE THREAD

**Issue by VinkenCheng** [miniers/safari2aria#21]
百度盘下载名字包含中文的文件时，名字中的中文部分会被转换成unicode码，这个怎么解决？能自动转换回来中文吗？

**Comment by miniers** [comment]
README已经有说明
注意事项

请在aria2c的配置文件中加入如下配置,用以开启百度云和迅雷离线导出时自动更改下载文件名
content-disposition-default-utf8=true

**Comment by VinkenCheng** [comment]
@miniers aria2c的配置我已经加入了这个参数，但是下载还是不会自动转中文
```
如：天赋异禀.The Gifted.S01E09.720p-天天美剧字幕组
下载文件名：%E5%A4%A9%E8%B5%8B%E5%BC%82%E7%A6%80.The+Gifted.S01E09.720p-%E5%A4%A9%E5%A4%A9%E7%BE%8E%E5%89%A7%E5%AD%97%E5%B9%95%E7%BB%84
```

**Comment by wilsonlih** [comment]
想请问一下，这项要在哪里添加啊？我找不到。

**Comment by VinkenCheng** [comment]
@miniers 
https://aria2.github.io/manual/en/html/aria2c.html#files
> By default, aria2 checks whether the legacy path $HOME/.aria2/aria2.conf is present, otherwise it parses $XDG_CONFIG_HOME/aria2/aria2.conf as its configuration file. You can specify the path to configuration file using --conf-path option. If you don’t want to use the configuration file, use --no-conf option.
