### ISSUE TITLE
是否可以考虑百度云盘的整目录下载功能

### ISSUE THREAD

**Issue by jesset** [miniers/safari2aria#22]
1. 目前只能一层层进目录，逐个点击文件下载，包含多个目录子目录的情况会比较繁琐；
2. 如果是目录的话，百度盘会自动打包成 `pack.zip` ，但此方式下载并不稳定容易断，而且多个打包会重名不易于管理；

**Comment by miniers** [comment]
短时间内没有精力增加功能了
批量下载可以使用 https://github.com/acgotaku/BaiduExporter
