### ISSUE TITLE
最近幾天百度雲無法下載了

### ISSUE THREAD

**Issue by phoenixwu** [miniers/safari2aria#24]
出現download error（前陣子都OK）

**Comment by hufan-akari** [comment]
https://github.com/acgotaku/BaiduExporter/issues/547

**Comment by phoenixwu** [comment]
好像得用aria2c的command line指定cookie或referrer才行（但也有人說不行 :P）

**Comment by miniers** [comment]
可以尝试更改ua,插件对百度盘并不是解析下载地址，而是拦截浏览器的下载事件，所以理论上只要还能在浏览器直接下载，应该是没问题的😂，不过最近其他事多，也没折腾过

**Comment by miniers** [comment]
抽空看了下，加了点参数来解决这个问题
更新到 2.9.5试试

**Comment by miniers** [comment]
![snipaste_20180122_131429](https://user-images.githubusercontent.com/2039910/35206247-4cb75128-ff76-11e7-8c45-69c357b07147.jpg)

**Comment by phoenixwu** [comment]
加入BDUSS cookie就OK了！THANX
