### ISSUE TITLE
默认单线程？能出个多线程的设置吗？

### ISSUE THREAD

**Issue by VinkenCheng** [miniers/safari2aria#25]
@miniers 默认是单线程？能出个多线程的设置吗？或者改默认最大线程？辣鸡baidupan单线程限速10-100kb。。。。

**Comment by miniers** [comment]
这个需要在aria2的配置中设置的，不过官方的aria2最大限制了16线程，你需要自己改源码来去除这个限制

**Comment by miniers** [comment]
https://github.com/miniers/aria2dsm/blob/master/Dockerfile
可以看看这个

**Comment by VinkenCheng** [comment]
@miniers 我aria2配置里面是写了16线程的，用WebUI手动添加任务也是16线程，但是safari2aria添加了几个任务貌似都是单线程的

**Comment by VinkenCheng** [comment]
刚更新完系统，现在添加任务恢复到最高的16线程了，可能是之前误操作了，更新系统重启之后重新读取配置恢复到16线程了
