### ISSUE TITLE
[BUG]对于是否可下载的url判定有问题

### ISSUE THREAD

**Issue by hufan-akari** [miniers/safari2aria#27]
直接判断url会有是否符合 filetype 会有 corner case.
我遇到的情况是，跳转 `https://lrc-maker.github.io/?audioSrc=http%3A%2F%2Fexample.com%2Fexample.mp3` 会意外触发下载。

应该对 url 进行解析，忽略 searchParms ,只处理 pathname.

**Comment by hufan-akari** [comment]
endsWith 写成了endswith, 真是抱歉哈。

**Comment by miniers** [comment]
😂发烧了也没注意看😂
