### ISSUE TITLE
支持配置多个user-agent

### ISSUE THREAD

**Issue by PhiloZhang** [miniers/safari2aria#3]
很喜欢你的插件。
在平时使用过程中，我经常要使用不同的user-agent，比如下百度云的时候使用百度云的UA，下PT的时候使用Transmission的UA，普通下载的时候使用Safari的UA。所以希望可以支持支持配置多个user-agent，并且可以在图标里快速切换。

**Comment by miniers** [comment]
好的，有时间我会想想如何更好的切换ua

**Comment by miniers** [comment]
added in v2.7
