### ISSUE TITLE
我是最新版系统10.13.4，插件装不上

### ISSUE THREAD

**Issue by siwday** [miniers/safari2aria#35]
每次安装都会打开浏览器让我选择信任，但是信任之后没有任何插件被安装

**Comment by lanceflee** [comment]
System Preferences-->Keyboard-->shortcuts-->(bottom)
Full Keyboard Access: All controls(selected)

And then, Press Tab to switch on "trust" while adding an extension,
Press Space key to confirm.

**Comment by keplerkepler** [comment]
macOS Mojave如何恢复无法使用的Safari旧扩展https://new.qq.com/omn/20180929/20180929A15FZF.html

**Comment by kabar1** [comment]
新版的safari没扩展生成器了，怎么破？
