### ISSUE TITLE
不支持safari 12。

### ISSUE THREAD

**Issue by yolin11** [miniers/safari2aria#39]
safari 12不支持之前的插件了，希望开发者更新一下。

**Comment by CarlosEvo** [comment]
[Related Document](https://developer.apple.com/safari/whats-new/)

> # Safari Extensions
> + Deprecated .safariextz-style Safari Extensions
>     - Support for .safariextz-style Safari Extensions installed from the Safari Extensions Gallery is deprecated with Safari 12 on macOS. Submissions to the Safari Extensions Gallery will no longer be accepted after December 2018. Developers are encouraged to transition to Safari App Extensions.
> + Disabled canLoad Safari Extensions on first launch
>     - Safari Extensions that make use of the canLoad event will be disabled on first launch and users will be notified with a warning that their use is harmful to performance. These extensions can be enabled in Safari Extensions preferences. Developers are encouraged to move to Content Blocker Extensions.
> + Removed Support for Developer-signed .safariextz Safari Extensions
>     - Support for developer-signed .safariextz Safari Extensions in Safari 12 on macOS has been removed. They no longer appear in Safari preferences and cannot be enabled. On first launch users will receive a warning notification and these extension will not load.

**Comment by CheYanShang** [comment]
还可以用：
----------
起因
某天在用Safari的时候想用Markdown-Here这个插件，但是下载之后发现不能像Chrome那样直接拖放进浏览器实现安装。于是网上搜了一下——都是在说怎么在Safari自带的扩展商店下载和安装插件，对于不在商店里的插件则没有人说怎么办？官方扩展商店还用你教？

怎么办呢？在V2EX上有一个帖子，我顺着他的思路做好了，想着肯定会有别人也遇到这样的问题，索性把过程写下来，方便其他和我一样的小白用户。本操作指南是在 Safari 版本 9.1.1 (11601.6.17)环境下进行的。
教程
1. 如上图所示，点开偏好设置，勾选在菜单栏中显示”开发“菜单。


2. 点击开发菜单，进入”显示扩展创建器“选项。

3. 把下载的后缀为safariextz的文件解压缩，在”显示扩展创建器“页面点击”添加扩展“，找到并选中解压缩的文件夹。

4. 点击右上角的”安装“，会弹出一个提示，点击安装，会继续弹出一个权限窗口，输入本机用户的密码，即可完成该插件的安装。

以上。
----

**Comment by miniers** [comment]
😂尝试提交插件商店了，不过没精力后续维护了，能通过就过，不能通过我也没办法了

**Comment by lvhe19880210** [comment]
> 尝试提交插件商店了，不过没精力后续维护了，能通过就过，不能通过我也没办法了

赞，不知道多久能通过，苹果上架效率一向很慢
