### ISSUE TITLE
升級到Safari 12之後無法使用了

### ISSUE THREAD

**Issue by phoenixwu** [miniers/safari2aria#40]
之後safari的extension似乎都得到App Store下載了
囧

**Comment by duhd1993** [comment]
可以用Develop mode加载解压后的extension，但是很不方便...Apple一定要割开发者的这个羊毛

**Comment by yefeiyu** [comment]
“safari2aria” is no longer supported. You can find newer extensions reviewed by Apple in the App Store or Safari Extensions Gallery

**Comment by keplerkepler** [comment]
macOS Mojave如何恢复无法使用的Safari旧扩展https://new.qq.com/omn/20180929/20180929A15FZF.html

**Comment by windrunner414** [comment]
开发模式加载貌似重启之后又要重新手动运行扩展，有没有什么解决办法？

**Comment by snow212-cn** [comment]
一年了，为啥作者miniers藏猫猫，不出来解决？

**Comment by miniers** [comment]
> 一年了，为啥作者miniers藏猫猫，不出来解决？

尝试提交插件商店，审核的人不会aria2得搭建，我也没办法
如果你有能力，欢迎fork后提交商店
