### ISSUE TITLE
localhost未连接

### ISSUE THREAD

**Issue by ChristinaCheung1225** [miniers/safari2aria#6]
百度云的视频文件，长按shift点下载一直显示，fail to added to localhost
目前点下载可以直接拦截了。。但只是在Safari自己的下载列表里，然后文件名是乱码。。。

**Comment by miniers** [comment]
能否给出视频链接？
还有本机的aria2是否已经启动？

**Comment by ChristinaCheung1225** [comment]
aria2在哪里启动？
以下链接：
https://d11.baidupcs.com/file/077b1953f851edcd9579ec862b689d83?bkt=p3-0000d84aceb3c656a79b65807cc7e15a6c2a&xcode=64f10778bfce86ca804cff82440f35a69b808a3eee438c20837047dfb5e85c39&fid=3289493842-250528-1079946321670536&time=1500080100&sign=FDTAXGERLBHS-DCb740ccc5511e5e8fedcff06b081203-jeriJOtHLHyZ4QJPQSfFfsY7sKM%3D&to=d11&size=2346995019&sta_dx=2346995019&sta_cs=4878&sta_ft=mkv&sta_ct=6&sta_mt=5&fm2=MH,Yangquan,Netizen-anywhere,,shandong,ce&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000d84aceb3c656a79b65807cc7e15a6c2a&sl=83034191&expires=8h&rt=pr&r=148390061&mlogid=4531217389486978444&vuk=3289493842&vbdid=853551456&fin=布达佩斯大饭店.720p.中英字幕.mkv&rtype=1&iv=0&dp-logid=4531217389486978444&dp-callid=0.1.1&hps=1&csl=300&csign=xvDIJzVGxSxGpcpP56HAYiijzEI%3D&so=0&ut=6&uter=4&serv=1&by=themis

**Comment by miniers** [comment]
https://aria2.github.io
请先了解aria2，本项目仅仅是一个插件，无法封装aria2需要手工部署启动
