### ISSUE TITLE
不支持rpc的rpc-secret令牌校验？

### ISSUE THREAD

**Issue by okman523** [miniers/safari2aria#7]
不支持rpc的rpc-secret令牌校验？

**Comment by j84lee** [comment]
rpc-secret写在哪里?

**Comment by miniers** [comment]
截图和默认值都使用了token

**Comment by j84lee** [comment]
@miniers 你是说https://user-images.githubusercontent.com/2039910/27525469-bf00a3ac-5a70-11e7-891a-d382b12b7587.png 这张图? 写的格式是什么? token:然后是什么?怎么接ip地址?

**Comment by miniers** [comment]
http://token:123456@127.0.0.1:6800/jsonrpc
插件的默认值就是这个，应该很清晰了

**Comment by j84lee** [comment]
@miniers 谢谢,但是我的默认不是啊.. 奇怪
