### ISSUE TITLE
mini-toastr should be invisible by default

### ISSUE THREAD

**Issue by lpimem** [miniers/safari2aria#8]
<img width="774" alt="screen shot 2017-07-28 at 3 33 37 pm" src="https://user-images.githubusercontent.com/16951198/28735303-32c7129c-73aa-11e7-8421-5f4971cb8baa.png">

The injected mini-toastr div is blocking content on some websites.  It should be invisible by default. Or it should be injected only when needed, and removed when work is done. 

插件加入的DIV在一些网页上会挡住内容，应该默认设为 invisible (display:none?) , 或者只在需要显示时再创建，用完后销毁。

**Comment by miniers** [comment]
thx, v2.9.1  fix it.
