### ISSUE TITLE
下载完成后, 没有提示?

### ISSUE THREAD

**Issue by foobra** [miniers/safari2aria#9]
右上角还是显示1, 点开后发现已经下载完成

**Comment by miniers** [comment]
请确保设置中当前aria2服务勾选了推送，如果没有勾选推送，在任务列表浮层关闭的情况下是不会主动连接aria2来获取任务状态的，如果开启了推送的情况还是出现这个问题，我会抽空解决下

**Comment by foobra** [comment]
勾选push后, ok了.
